Feature/initial setup
Per-Kristian/diceroll pull request #1
Opened 2024-03-27 09:29 UTC by Per-Kristian

2024-03-27 10:52 UTC, peterjohansen requested changes
Wrote a bunch of scrambled, initial thoughts. Didn't comment on everything because some of it might become irrelevant if you refactor a bit.

Also the level of scrutiny I used is a a lot higher than I would have used if this was from a student. I'm guessing that's what you are after.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/App.java
> +package com.perk;
Usually one would have another level in the package for the specific project.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/App.java
> +            out.println(STR."You rolled \{result}, congrats! Thanks for playing :)");
Nasty syntax.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/PredictionReader.java
> +            final var prediction = console().readLine();
I would just use a `Scanner` here that looks at `System.in`. This `Console` class is news to me, but it seems in certain conditions it won't be available, like when I try to run it in IntelliJ.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/PredictionReader.java
> +            final var prediction = console().readLine();
Also, a nice class you could create is a class that is responsible for communication with the user (input and output). That way you could also easily switch out the implementation to use something other than `System.in` and `System.out` instead of being tightly coupled to them.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/PredictionReader.java
> +    private static void printError(final RuntimeException e) throws InterruptedException {
When your app has end users, you should explicitly catch certain exceptions and map them to custom error messages for the user. Using the exception message like this works of course, but it's not a good solution because you don't know what can be shown to the user. And that's thinking only of UX, not security issues.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/Die.java
> +        this.lastResult = new Random().nextInt(1, 7);
Slightly clearer to do `new Random().nextInt(6) + 1` here in my opinion.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/Die.java
> +        return lastResult;
Here you should either:
1. Clearly document in which cases the result can be `null`.
2. Return `Optional<Integer>` instead, and also document.
3. Just ditch this method, make `Die` stateless and return `int` in the `roll` method.

I would go for option 3. Even though this is a simple example, having a state makes things more complex, and in this case it doesn't seem unnecessary.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/Die.java
> +        this.lastResult = new Random().nextInt(1, 7);
I would also move creation of the `Random` outside this method since it is meant to be reused.

You could even take it in as a construction parameter so it's possible to set the seed for the rolling. Probably good to have a default constructor that creates the `Random` also if you do that, though. I don't think it's necessary in this case.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/Die.java
> +        return lastResult;
If you make `Die` stateless, then you could also move the min and max value constants into this class and expose them as getters. Then you would pass the `Die` object to other parts of your app. That opens up for changing the amount of points on your die without having to refactor anything.

2024-03-27 10:52 UTC, peterjohansen commented on pom.xml
> +      <artifactId>slf4j-simple</artifactId>
Are these SLF4J loggers even used? Would remove them if not.

If they are used, consider setting this one to test scope. It depends on whether you want to provide logging as part of your whole app, or if you just want logging for testing.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/App.java
> +    private static Integer roll(final Die die) throws InterruptedException {
I would avoid throwing check exceptions. Wrapping them in a runtime exception is better in always every situation. They are a hassle to deal with both in your own code and if anyone uses your code.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/PredictionValidator.java
> +            throw new UnsupportedOperationException(STR."Invalid prediction. Your guess should be \{MIN} through \{MAX}.");
`IllegalArgumentException` is the correct exception to use here.

2024-03-27 10:52 UTC, peterjohansen commented on src/main/java/com/perk/PredictionValidator.java
> +        return validate(Integer.parseInt(prediction));
I wrote it in another comment, but consider creating a class for user I/O. It can handle stuff like asking the user for an integer and re-asking if they enter an illegal value. That should be separate from the business logic validation (1-6), preferably.

2024-03-28 23:28 UTC, Per-Kristian commented on src/main/java/com/perk/PredictionValidator.java
> +        return validate(Integer.parseInt(prediction));
This is interesting, because I had a class like this earlier. It was the "Prompt" class I told you about at the office, but I removed it after your reaction to it, lol.
Was it just the name of the class you didn't like? It basically did what you described here.

2024-03-28 23:28 UTC, Per-Kristian commented on src/main/java/com/perk/PredictionReader.java
> +    private static void printError(final RuntimeException e) throws InterruptedException {
Yeah, as I mentioned earlier, I was aware of this when I wrote it, I just didn't bother too much at the time with neither the UX or Security issues. But yeah, I'll just fix it, might as well.

2024-03-28 23:28 UTC, Per-Kristian commented on src/main/java/com/perk/PredictionReader.java
> +            final var prediction = console().readLine();
Strange that it doesn't work for you in IntelliJ. I'm not sure what causes it, but my IntelliJ is using java.exe, while yours is probably using javaw which isn't associated with a console. IntelliJ using java.exe seems to be the anomaly, so I'm not sure why mine does that. I wonder if it could be caused by different IntelliJ versions, or maybe it has something to do with the fact that I installed JDK 22 via IntelliJ instead of manually.

2024-03-28 23:28 UTC, Per-Kristian commented on src/main/java/com/perk/Die.java
> +        return lastResult;
This is one of those things that I mentioned earlier. This class was initially stateless, but then I just stored the state 'just in case'. Not too steady at balancing making unused stuff 'just in case' vs not overdoing stuff by predicting future use cases.

I guess refactoring to facilitate for changing the points could be a case of predicting future use cases, but I think it makes sense and I like it. I'll make the change.

I'm curious though, would you do that from the get-go in an app? Feels like something we'd do more often if this were a library.

2024-03-28 23:28 UTC, Per-Kristian commented on src/main/java/com/perk/App.java
> +            out.println(STR."You rolled \{result}, congrats! Thanks for playing :)");
What, the string template syntax? This is probably going to become the standard pretty soon, no? It's in preview atm: https://blog.jetbrains.com/idea/2023/11/string-templates-in-java-why-should-you-care/

It looks better with the variable highlighting in IntelliJ:
![image](https://github.com/Per-Kristian/diceroll/assets/6986585/caf73f0c-363c-42df-a92e-614e228788e9)

2024-03-28 23:28 UTC, Per-Kristian commented on src/main/java/com/perk/App.java
> +package com.perk;
Yeah I got so lost in trying to find out what to name my top level packages that I forgot the project package.

2024-03-28 23:28 UTC, Per-Kristian commented on pom.xml
> +      <artifactId>slf4j-simple</artifactId>
Nice find. Nah, I used them briefly but removed the log statements and forgot the dependencies. I did use them in the source code, but good point about test scope. Will keep that in mind for later.

2024-03-29 08:06 UTC, peterjohansen commented on src/main/java/com/perk/Die.java
> +        return lastResult;
In this case I would make it stateless regardless of whether is this is a library or to predict future use cases.

2024-03-29 08:07 UTC, peterjohansen commented on src/main/java/com/perk/PredictionValidator.java
> +        return validate(Integer.parseInt(prediction));
Probably. `Prompt` sounds like a class that that only asks for a single input per instance.

2024-04-01 11:43 UTC, Per-Kristian commented on src/main/java/com/perk/Die.java
> +        this.lastResult = new Random().nextInt(1, 7);
Actually the nextInt point is kind of interesting. I changed it, but I just noticed that when I'm reading it now, I feel like adding 1 to the result of nextInt is a bit more confusing. The reason is that `nextInt(1, 7)`, or what would now have been `this.lastResult = nextInt(minValue, maxValue + 1)` gives a hint to the reader that the `nextInt` method handles the two parameters differently, i.e. that the first parameter is inclusive and the second parameter is exclusive. On the other hand, `this.lastResult = nextInt(maxValue) + 1` or `this.lastResult = nextInt(minValue, maxValue) + 1` makes it look like the author is arbitrarily adding 1 to the result, which raises questions about why they would do that. Unless the reader knows how `nextInt` works by heart, they would have to read the nextInt documentation to figure out why the author would add 1 to the returned value.

Regardless though, it also feels to me like using the API as it's meant to is better than using workarounds on the outside. What do you think?

2024-04-02 07:59 UTC, peterjohansen requested changes
More comménts.

2024-04-02 07:59 UTC, peterjohansen commented on .gitignore
> +.idea/
Some files in `.idea/`is recommended to include now:
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

2024-04-02 07:59 UTC, peterjohansen commented on pom.xml
> +  <url>http://maven.apache.org</url>
Did you add this? I have never seen it before.

2024-04-02 07:59 UTC, peterjohansen commented on pom.xml
> +    <slf4j.version>1.7.36</slf4j.version>
Remnant from last removal.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +    final Die die;
`private`

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +    public static void main(String[] args) {
`static` methods should be placed at the top of the class.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +    private Integer getPrediction() {
When asking the user for input I usually use another verb than `get` to make it clear that this blocks execution. Typically like `askUserForPrediction` or something.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +    private Integer getPrediction() {
Unless you have a very good reason, always use `int` over `Integer`. Especially in return values because you should use `Optional<Integer>` if you need it to be optional.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +        final var io = new PlayerInteraction();
Should reuse the instance you store in the constructor.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +        } catch (InterruptedException e) {
`final`

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +        final var io = new PlayerInteraction();
This applies to several places in this class.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +    private void wait(final Duration duration) {
I would avoid using `wait` as the method name because it's the name of a method in the `Object` class. It'll work since it has a new parameter, but I would just use `sleep` anyway.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +            throw new RuntimeException(e);
There is almost never a valid reason to throw `RuntimeException` directly. If `InterruptedException` occurs then the user interrupted the application, so I would respond accordingly.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +            sleep(Duration.ofSeconds(2));
Should use your method that catches the exception.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +    private void wait(final Duration duration) {
Also, I would consider moving this method into the `PlayerInteraction` class. It's directly related to the interaction with the player.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/Die.java
> +    private final Integer lowestValue;
Use `int` here because these should never be `null`.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/Die.java
> +    public Die(final Integer lowestValue, final Integer highestValue, final Random random) {
Should throw an `IllegalArgumentException` if the lowest value is greater than the highest value.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/Die.java
> +    public Die(final Integer lowestValue, final Integer highestValue, final Random random) {
Thinking about it, it's a bit weird that the `Die` object holds a `Random`. Might be better to accept that as an argument in the `roll` method. If you do that, I would also get rid of the builder because it's overkill.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/Die.java
> +    public Die(final Integer lowestValue, final Integer highestValue, final Random random) {
If you want the class to be usable as part of a library, and easily useable for other purposes, you could have another version of `roll` with no parameters that uses some `Math.nextInt` method.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/Die.java
> +    public Die(final Integer lowestValue, final Integer highestValue, final Random random) {
Another thing you could do is to create a static factory method to create a `Die` with a single parameter, which is the amount of dots, since you almost never need a die with another minimum than zero.

The plus with static factory methods is that you basically create a named constructor.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/PlayerInteraction.java
> +        this(System.in, System.out);
Nice.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/PlayerInteraction.java
> +public class PlayerInteraction {
You should implement `AutoCloseable` here and make sure the reader and writer are closed. Then in the class that is responsible for the `PlayerInteraction` instance, instantiate it in a try-with-resources or just make sure it's properly closed in another way.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/PlayerInteraction.java
> +        writer.println(requireNonNull(message));
It's mostly personal preference but I typically find it clearer to do the null-check on its own line. The main exception is when assigning variables in a constructor.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/GuessValidator.java
> +public class GuessValidator {
I think you should just drop this class and instead do the validation in the main class, using some method in the `PlayerInteraction` class that lets you ask for an integer in a range.

2024-04-02 07:59 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/PlayerInteraction.java
> +    public <T> T requireInput(final String prompt, final Function<String, T> parser, final BiFunction<Exception, String, String> exceptionHandler) {
Is this used?

2024-04-05 14:11 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/PlayerInteraction.java
> +public class PlayerInteraction {
Actually, on second thought, I wouldn't do this. You generally shouldn't close streams that you didn't open, and we opened neither `System.in` nor `System.out`.

2024-04-05 14:15 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/Die.java
> +    public Die(final Integer lowestValue, final Integer highestValue, final Random random) {
Maybe you could just drop the lowest value thing also.

2024-04-06 11:44 UTC, Per-Kristian commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +        final var io = new PlayerInteraction();
Yeah, it's because I initially stored it as a class member, but then figured maybe I should create a new one per interaction with the user. I think the "PlayerInteraction" name of the class caused me to even make that consideration, which I think was dumb. If I had called it Console or something, I would never have created new instances like this. I'll rename it.

2024-04-06 11:44 UTC, Per-Kristian commented on pom.xml
> +  <url>http://maven.apache.org</url>
Nah, prob was added by the IntelliJ maven wizard

2024-04-07 09:11 UTC, Per-Kristian commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +    public static void main(String[] args) {
![bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8 u7](https://github.com/Per-Kristian/diceroll/assets/6986585/36abbedf-6591-482a-b6c5-d82374bb8f5a)
https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2024-04-11 21:44 UTC, Per-Kristian commented on .gitignore
> +.idea/
For traceability, I'll just mention that we spoke about this comment IRL. I prefer gitignoring this until the need for sharing IDEA files arises.

2024-04-11 22:02 UTC, Per-Kristian commented on src/main/java/org/perk/diceroll/Die.java
> +    public Die(final Integer lowestValue, final Integer highestValue, final Random random) {
Assuming this suggestion is an alternative to dropping lowestValue since there's no real need for a static factory method when there's just one int parameter as far as I can tell

2024-04-12 12:21 UTC, peterjohansen requested changes

2024-04-12 12:21 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +            final var prediction = ui.requireInteger("Guess the die: ", die.getMin(), die.getMax());
I think I would keep input and output separate, except for maybe the most basic string prompts. It tends to really bloat the parameters.

2024-04-12 12:21 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/DiceRoll.java
> +                ui.writeLine(STR."You rolled \{result}, unlucky. Better luck next time.");
Is the user rolling or the computer?

2024-04-12 12:21 UTC, peterjohansen commented on src/main/java/org/perk/diceroll/Die.java
> +    private final int min;
Could just get rid off the minimum.

2024-04-15 05:46 UTC, peterjohansen requested changes

2024-04-15 05:46 UTC, peterjohansen commented on pom.xml
> +    <name>diceroll</name>
This is usually excluded because it defaults to the artifact ID.

2024-04-15 05:46 UTC, peterjohansen commented on src/test/java/org/perk/diceroll/DieTest.java
> +        assert(result == 1 || result == 2);
Should use `assertTrue` here.

You could technically write tests using only `assert`, but I've never seen it.

https://stackoverflow.com/a/2758645

2024-04-20 19:46 UTC, Per-Kristian commented on src/test/java/org/perk/diceroll/DieTest.java
> +        assert(result == 1 || result == 2);
Oops, this is just a brainfart. Meant to use assertTrue.

2024-04-22 07:23 UTC, peterjohansen commented
I suggest you build a runnable JAR.

2024-05-03 22:20 UTC, Per-Kristian commented
> I suggest you build a runnable JAR.

Uploaded here: https://github.com/Per-Kristian/diceroll/releases/tag/v1.0.0

2024-05-04 08:29 UTC, peterjohansen approved these changes

2024-05-04 10:44 UTC, merged